title: Ésto es Aburrido.Digital

description: >- # this means to ignore newlines until "baseurl:"
  Una página donde se habla de todo y de nada.
  
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-tactile
#theme: jekyll-theme-midnight
#theme: jekyll-theme-slate
